export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_COMPOSITE_PRODUCTS_REQUEST = 'GET_COMPOSITE_PRODUCTS_REQUEST';
export const GET_COMPOSITE_PRODUCTS_SUCCESS = 'GET_COMPOSITE_PRODUCTS_SUCCESS';
export const GET_COMPOSITE_PRODUCTS_FAILED = 'GET_COMPOSITE_PRODUCTS_FAILED';

export const GET_COMPOSITE_PRODUCT_REQUEST = 'GET_COMPOSITE_PRODUCT_REQUEST';
export const GET_COMPOSITE_PRODUCT_SUCCESS = 'GET_COMPOSITE_PRODUCT_SUCCESS';
export const GET_COMPOSITE_PRODUCT_FAILED = 'GET_COMPOSITE_PRODUCT_FAILED';

export const ADD_COMPOSITE_PRODUCTS_REQUEST = 'ADD_COMPOSITE_PRODUCTS_REQUEST';
export const ADD_COMPOSITE_PRODUCTS_SUCCESS = 'ADD_COMPOSITE_PRODUCTS_SUCCESS';
export const ADD_COMPOSITE_PRODUCTS_FAILED = 'ADD_COMPOSITE_PRODUCTS_FAILED';

export const EDIT_COMPOSITE_PRODUCTS_REQUEST = 'EDIT_COMPOSITE_PRODUCTS_REQUEST';
export const EDIT_COMPOSITE_PRODUCTS_SUCCESS = 'EDIT_COMPOSITE_PRODUCTS_SUCCESS';
export const EDIT_COMPOSITE_PRODUCTS_FAILED = 'EDIT_COMPOSITE_PRODUCTS_FAILED';